Revert "cpu_input_boost: Eliminate spin lock by using atomic cmpxchg loop"
Revert this for now to get this thing to compile and fix it later:
arch/arm64/include/asm/atomic.h:56:39: error: request for member 'counter' in something not a structure or union

This reverts commit 2667b3fc50af28283c2eac8cb883c14c33224cf7.